// generated by stringer -type Color src/github.com/Manozco/cards/card.go; DO NOT EDIT

package cards

import "fmt"

const _Color_name = "SpadeClubHeartDiamond"

var _Color_index = [...]uint8{0, 5, 9, 14, 21}

func (i Color) String() string {
	if i < 0 || i >= Color(len(_Color_index)-1) {
		return fmt.Sprintf("Color(%d)", i)
	}
	return _Color_name[_Color_index[i]:_Color_index[i+1]]
}
