// generated by stringer -type Face src/github.com/Manozco/cards/card.go; DO NOT EDIT

package cards

import "fmt"

const _Face_name = "TwoThreeFourFiveSixSevenEightNineTenJackQueenKingAce"

var _Face_index = [...]uint8{0, 3, 8, 12, 16, 19, 24, 29, 33, 36, 40, 45, 49, 52}

func (i Face) String() string {
	if i < 0 || i >= Face(len(_Face_index)-1) {
		return fmt.Sprintf("Face(%d)", i)
	}
	return _Face_name[_Face_index[i]:_Face_index[i+1]]
}
